version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=library_service.settings

  telegram-bot:
    build: .
    command: python manage.py run_telegram_bot
    depends_on:
      - redis
    environment:
      - TELEGRAM_API_KEY=your_api_key_here

  celery:
    build: .
    command: celery -A library_service worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - my_db:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:6
    ports:
      - "6380:6379"

volumes:
  my_db:
  my_media:
